on:
  schedule:
    - cron: '0 9 * * *'
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
      - run: deno lint 
      - name: Test
        run: |
          deno lint
          deno fmt --check
          deno task check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
      - run: |
          deno task test:coverage
          deno task show-coverage

  jsr-publish-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
      - run: deno publish --dry-run


  action-timeline:
    needs: 
      - test
      - check
      - jsr-publish-dry-run
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - uses: Kesin11/actions-timeline@v2
