on:
  schedule:
    - cron: '0 9 * * *'
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: '~/.bun/install/cache'
          key: ${{ runner.os }}-bun-${{ env.cache-name }}

      - name: Install dependencies
        run: bun install

      - name: Run lint
        run: bun run lint

      - name: Run test
        run: bun run test

      - name: Generate coverage
        run: bun run vitest --coverage

      - name: Report coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2.1.1
