on:
  schedule:
    - cron: '0 9 * * *'
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1

      - name: Test
        run: |
          deno task test
          deno task show-coverage

  action-timeline:
    needs: 
      - ci
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - uses: Kesin11/actions-timeline@v2
