on:
  schedule:
    - cron: "0 9 * * *"
  push:
  pull_request:

env:
  DENO_VERSION: 2.x
  NODE_VERSION: lts/*

permissions:
  contents: read
  pull-requests: write

jobs:
  check-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - run: deno lint
      - name: Test
        run: |
          deno lint
          deno task check
          deno task lint
          deno task test:coverage
          deno task coverage:lco
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe # v5.5.4
        with:
          file: ./coverage.lcov
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ryoppippi/str-fns

  jsr-publish-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - run: deno publish --dry-run

  action-timeline:
    needs:
      - check-test
      - jsr-publish-dry-run
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@e018cfefea60b4f44266998551211a35a58b8097 # v3.0.0
