on:
  schedule:
    - cron: '0 9 * * *'
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Run lint
        run: bun run lint

      - name: Run test
        run: bun test --coverage

      - name: Run typecheck
        run: bun run typecheck

  action-timeline:
    needs: 
      - ci
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - uses: Kesin11/actions-timeline@v2
